#cloud-config
package_update: true
package:
    - build-essentials
    - curl
    - file
    - git
    - nodejs
write_files:
    - owner: 'efrain:efrain'
      path: '/home/efrain/server.js'
      content: |
        const http = require('http');

        const hostname = '0.0.0.0';
        const port = 8000;

        const server = http.createServer((req, res) => {
            res.statusCode = 200;
            res.setHeader('Content-Type', 'text/plain');
            res.end('<h1>Hello Cloud Admin</h1>');
        });

        server.listen(port, hostname, () => {
            console.log(`Server running at http://${hostname}:${port}/`);
        });
runcmd:
    - cd '/home/efrain/'
    - node server.js